### ISSUE TITLE
`pip install nudnik==0.0.14` fails, error on requirements.txt

### ISSUE THREAD

**Issue by hagzag** [salosh/nudnik#44]
The issue is that setup.py expects the requirements.txt file to be present in the current working dir which basiaclly means a simepl pip install will not work see the error message I get during docker build:
```sh
docker build .
Sending build context to Docker daemon  413.7kB
Step 1/4 : FROM python:2.7-alpine
 ---> f901fc789b69
Step 2/4 : RUN pip install nudnik
 ---> Running in 88e5a2b87c87
Collecting nudnik
  Downloading https://files.pythonhosted.org/packages/fc/47/2c3aa8f4b6ea49da998c2cb31bb6c9dae829be2e9f04bce7ff7c801518d7/nudnik-0.0.14.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kCKest/nudnik/setup.py", line 33, in <module>
        with open('requirements.txt') as f:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-kCKest/nudnik/
The command '/bin/sh -c pip install nudnik' returned a non-zero code: 1
```

with a simpler Dockerfile:
```
FROM python:2.7-alpine

RUN pip install nudnik

EXPOSE 5410

ENTRYPOINT [ "nudnik" ]
```

**Comment by Saloshp** [comment]
Thats because I published the source tarball, rather than a "compiled" wheel,
please upgrade Nudnik version to https://pypi.org/project/nudnik/0.0.15/

**Comment by Saloshp** [comment]
@hagzag The requirement `grpcio-tools` requires `gcc`, I replaced it with the correct requirement `protobuf`.
Please download latest https://pypi.org/project/nudnik/0.0.16/,
Tested on a clean VM with no issues, please let me know if you still experience any..
